In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [69]:
df = pd.read_csv('./max/data/datos_inflacion.csv')

In [246]:
df = df.dropna()
df['t'] = range(len(df))
df['t2'] = df['t']**2
number_lags = 24
variables_lags = []
for v in ['Indice_general', 'No_subyacente', 'Subyacente']:
    for lag in range(1, number_lags + 1):
        df['L' + str(lag) + '.' + v] = df[v].shift(lag)
        variables_lags.append('L' + str(lag) + '.' + v)
df = df.dropna()
df['mes'] = df['TIME_PERIOD'].astype(str).str[5:7]
dummies = pd.get_dummies(df['mes'])#.values
Y = df[['inf']].values
# variables = ['Indice_general', 'No_subyacente', 'Subyacente']
# variables += variables_lags
# variables += ['t', 't2']
print(df[variables].columns)
# X = df[['Indice_general',
#  'No_subyacente',
#  'Subyacente',
# #  't',
# #  't2',
#  'L18.Indice_general',
#  'L18.No_subyacente',
#  'mes_01',
#  'mes_02',
#  'mes_03',
#  'mes_04',
#  'mes_05',
#  'mes_06',
#  'mes_07',
#  'mes_08',
#  'mes_09',
#  'mes_10',
#  'mes_11',
#  'mes_12']].values
X = np.concatenate([X, dummies[:,1:]], axis=1)
X = sm.add_constant(X)

model = sm.OLS(Y,X)
results = model.fit()
results.params
print(results.summary())
df['predict'] = results.predict(X)
df[['inf', 'predict']].plot()

Index(['Indice_general', 'No_subyacente', 'Subyacente', 't', 't2',
       'L1.Indice_general'],
      dtype='object')

InvalidIndexError: (slice(None, None, None), slice(1, None, None))

In [245]:
dummies

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=uint8)

In [219]:
inflaciones_23 = pd.read_csv('./data/inflaciones_2023.csv')

In [220]:
#inflaciones_23 = inflaciones_23.dropna()
inflaciones_23['t'] = range(len(inflaciones_23))
inflaciones_23['t2'] = inflaciones_23['t']**2
number_lags = 24
variables_lags = []
for v in ['Indice_general', 'Subyacente']:
    for lag in range(1, number_lags + 1):
        inflaciones_23['L' + str(lag) + '.' + v] = inflaciones_23[v].shift(lag)
        variables_lags.append('L' + str(lag) + '.' + v)
#inflaciones_23 = inflaciones_23.dropna()
inflaciones_23['mes'] = inflaciones_23['TIME_PERIOD'].astype(str).str[5:7]
inflaciones_23 = inflaciones_23.join(pd.get_dummies(inflaciones_23['mes'], prefix='mes'))

In [225]:
inflaciones_23 = inflaciones_23.loc[132:]

In [230]:
X

,const,Indice_general,Subyacente,t,t2,L18.Indice_general,L18.Subyacente,mes_01,mes_02,mes_03,mes_04,mes_05,mes_06,mes_07,mes_08,mes_09,mes_10,mes_11,mes_12
132,1.0,7.81,8.26,132,17424,5.81,4.69,1,0,0,0,0,0,0,0,0,0,0,0
133,1.0,7.43,8.01,133,17689,5.59,4.80,0,1,0,0,0,0,0,0,0,0,0,0
134,1.0,6.93,7.75,134,17956,6.01,4.95,0,0,1,0,0,0,0,0,0,0,0,0
135,1.0,6.41,7.37,135,18225,6.25,5.21,0,0,0,1,0,0,0,0,0,0,0,0
136,1.0,6.18,7.11,136,18496,7.37,5.68,0,0,0,0,1,0,0,0,0,0,0,0
137,1.0,5.68,6.71,137,18769,7.35,5.95,0,0,0,0,0,1,0,0,0,0,0,0
138,1.0,5.36,6.43,138,19044,7.06,6.22,0,0,0,0,0,0,1,0,0,0,0,0
139,1.0,5.01,5.96,139,19321,7.28,6.61,0,0,0,0,0,0,0,1,0,0,0,0
140,1.0,4.82,5.66,140,19600,7.45,6.80,0,0,0,0,0,0,0,0,1,0,0,0
141,1.0,4.78,5.35,141,19881,7.67,7.24,0,0,0,0,0,0,0,0,0,1,0,0
142,1.0,4.88,5.17,142,20164,7.65,7.30,0,0,0,0,0,0,0,0,0,0,1,0
143,1.0,5.01,4.95,143,20449,7.98,7.52,0,0,0,0,0,0,0,0,0,0,0,1

In [229]:
X = inflaciones_23[['Indice_general',
 'Subyacente',
 't',
 't2',
 'L18.Indice_general',
 'L18.Subyacente',
 'mes_01',
 'mes_02',
 'mes_03',
 'mes_04',
 'mes_05',
 'mes_06',
 'mes_07',
 'mes_08',
 'mes_09',
 'mes_10',
 'mes_11',
 'mes_12']]
Y = inflaciones_23[['inflacion']].values
# variables = ['Indice_general', 'No_subyacente', 'Subyacente']
# variables += variables_lags
# variables += ['t', 't2']
print(df[variables].columns)
X = sm.add_constant(X)
model = sm.OLS(Y,X)
results = model.fit()
results.params
print(results.summary())
df['predict'] = results.predict(X)
df[['inflacion', 'predict']].plot()

Index(['Indice_general', 'No_subyacente', 'Subyacente', 't', 't2',
       'L20.Indice_general', 'L20.Subyacente'],
      dtype='object')
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                         nan
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                       nan
Date:                Thu, 26 Jan 2023   Prob (F-statistic):                nan
Time:                        17:37:41   Log-Likelihood:                    nan
No. Observations:                  12   AIC:                               nan
Df Residuals:                       0   BIC:                               nan
Df Model:                          11
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                     nan        nan        nan        nan         nan         nan
Indice_general            nan        nan        nan        nan         nan         nan
Subyacente                nan        nan        nan        nan         nan         nan
t                         nan        nan        nan        nan         nan         nan
t2                        nan        nan        nan        nan         nan         nan
L18.Indice_general        nan        nan        nan        nan         nan         nan
L18.Subyacente            nan        nan        nan        nan         nan         nan
mes_01                    nan        nan        nan        nan         nan         nan
mes_02                    nan        nan        nan        nan         nan         nan
mes_03                    nan        nan        nan        nan         nan         nan
mes_04                    nan        nan        nan        nan         nan         nan
mes_05                    nan        nan        nan        nan         nan         nan
mes_06                    nan        nan        nan        nan         nan         nan
mes_07                    nan        nan        nan        nan         nan         nan
mes_08                    nan        nan        nan        nan         nan         nan
mes_09                    nan        nan        nan        nan         nan         nan
mes_10                    nan        nan        nan        nan         nan         nan
mes_11                    nan        nan        nan        nan         nan         nan
mes_12                    nan        nan        nan        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                     nan
Prob(Omnibus):                    nan   Jarque-Bera (JB):                  nan
Skew:                             nan   Prob(JB):                          nan
Kurtosis:                         nan   Cond. No.                     6.56e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.
[3] The condition number is large, 6.56e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

/Users/aleistermontfort/opt/anaconda3/envs/data_test/lib/python3.10/site-packages/scipy/stats/stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=12
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/Users/aleistermontfort/opt/anaconda3/envs/data_test/lib/python3.10/site-packages/statsmodels/regression/linear_model.py:1765: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)

KeyError: "['inflacion'] not in index"

In [14]:
results.predict(list(X[-10:]))

array([12.84301247, 11.76685117, 12.72375441, 14.5006963 , 12.93328589,
       15.70432422, 14.20618362, 13.94540028, 16.05005383, 16.90827087])

In [31]:
pd.get_dummies(df['mes'], prefix='mes').columns

Index(['mes_01', 'mes_02', 'mes_03', 'mes_04', 'mes_05', 'mes_06', 'mes_07',
       'mes_08', 'mes_09', 'mes_10', 'mes_11', 'mes_12'],
      dtype='object')

In [28]:
df.join(pd.get_dummies(df['mes'], prefix='mes'))

,TIME_PERIOD,Indice_general,No_subyacente,Subyacente,inf,t,t2,L1.Indice_general,L2.Indice_general,L3.Indice_general,...,mes_03,mes_04,mes_05,mes_06,mes_07,mes_08,mes_09,mes_10,mes_11,mes_12
39,2015-04-01,3.06,5.46,2.31,6.167245,39,1521,3.14,3.00,3.07,...,0,1,0,0,0,0,0,0,0,0
40,2015-05-01,2.88,4.64,2.33,-1.260038,40,1600,3.06,3.14,3.00,...,0,0,1,0,0,0,0,0,0,0
41,2015-06-01,2.87,4.63,2.33,-3.009526,41,1681,2.88,3.06,3.14,...,0,0,0,1,0,0,0,0,0,0
42,2015-07-01,2.74,4.12,2.31,-0.478386,42,1764,2.87,2.88,3.06,...,0,0,0,0,1,0,0,0,0,0
43,2015-08-01,2.59,3.51,2.30,-3.377370,43,1849,2.74,2.87,2.88,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,2022-06-01,7.99,9.47,7.49,15.477534,125,15625,7.65,7.68,7.45,...,0,0,0,1,0,0,0,0,0,0
126,2022-07-01,8.15,9.65,7.65,15.778238,126,15876,7.99,7.65,7.68,...,0,0,0,0,1,0,0,0,0,0
127,2022-08-01,8.70,10.65,8.05,14.338067,127,16129,8.15,7.99,7.65,...,0,0,0,0,0,1,0,0,0,0
128,2022-09-01,8.70,9.96,8.28,16.041001,128,16384,8.70,8.15,7.99,...,0,0,0,0,0,0,1,0,0,0
129,2022-10-01,8.41,8.36,8.42,16.101267,129,16641,8.70,8.70,8.15,...,0,0,0,0,0,0,0,1,0,0

In [116]:
X_train.shape

(117, 19)

In [117]:
X_test.shape()

TypeError: 'tuple' object is not callable

In [150]:
from tqdm import tqdm

In [234]:
# df = pd.read_csv('./max/data/datos_inflacion.csv')

# max_lags = 20
# variables_lags = []
# horizon = 12
# df = df.dropna()
# df['t'] = range(len(df))
# df['t2'] = df['t']**2
# df['mes'] = df['TIME_PERIOD'].astype(str).str[5:7]

# df = df.join(pd.get_dummies(df['mes'], prefix='mes'))
results_list=[]
counter=0
for lag in tqdm(range(1, max_lags + 1)):
    df = pd.read_csv('./max/data/datos_inflacion.csv')

max_lags = 20
variables_lags = []
horizon = 12
df = df.dropna()
df['t'] = range(len(df))
df['t2'] = df['t']**2
df['mes'] = df['TIME_PERIOD'].astype(str).str[5:7]

df = df.join(pd.get_dummies(df['mes'], prefix='mes'))
    lag_results=[]
    for v in ['Indice_general', 'No_subyacente', 'Subyacente']:
        df['L' + str(lag) + '.' + v] = df[v].shift(lag)
        variables_lags.append('L' + str(lag) + '.' + v)
        df = df.dropna()
        
        #dummies = pd.get_dummies(df['mes']).values
        dummies = pd.get_dummies(df['mes'], prefix='mes').columns
        


        variables = ['Indice_general', 'No_subyacente', 'Subyacente','t', 't2']
        variables += variables_lags
        i=i+1
        
        #print(df[variables].columns)
        
        for number in range(2):
            simple_list=[]
            if number==0:
                #print(i)
                X_train = df[variables + list(dummies)]
                X_train = X_train[:-horizon].values
                X_train = sm.add_constant(X_train)
             
                X_test = df[-horizon:]
                X_test = df[variables + list(dummies)].values
                X_test = sm.add_constant(X_test)
                
                Y_train = df[['inf']][:-horizon].values
                Y_test = df[['inf']][-horizon:].values
                Y_test=Y_test.reshape((horizon, ))
                #X = np.concatenate([X, dummies[:,1:]], axis=1)
                

                model_trained = sm.OLS(Y_train,X_train)
                results = model_trained.fit()
                results.params
                y_hat = results.predict(X_test[-horizon:])
                #print(results.summary())
                ssr =np.sum(np.square(np.subtract(y_hat, Y_test)))
                variables_model = variables + dummies.to_list()
                counter = counter+1
                simple_list.append(variables_model)
                simple_list.append(ssr)
                simple_list.append(results)
                results_list.append(simple_list)
                print(X_test.shape)
            else:
                simple_list=[]
                X_train = df[variables]
                X_train = X_train[:-horizon].values
                X_train = sm.add_constant(X_train)
              
                X_test = df[-horizon:]
                X_test = df[variables].values
                X_test = sm.add_constant(X_test)
                
                Y_train = df[['inf']][:-horizon].values
                Y_test = df[['inf']][-horizon:].values
                Y_test=Y_test.reshape((horizon, ))
                #X = np.concatenate([X, dummies[:,1:]], axis=1)
                
                X_train = sm.add_constant(X_train)

                model_trained = sm.OLS(Y_train,X_train)
                results = model_trained.fit()
                results.params
                y_hat = results.predict(X_test[-horizon:])##########
                ssr=np.sum(np.square(np.subtract(y_hat, Y_test)))
                variables_model = variables + dummies.to_list()
                counter = counter+1
                simple_list.append(variables_model)
                simple_list.append(ssr)
                simple_list.append(results)
                results_list.append(simple_list)
                print(X_test.shape)
                #print(results.summary())

IndentationError: unexpected indent (3107064808.py, line 26)

In [191]:
pd.DataFrame(results_list).sort_values(1).loc[71][0]

['Indice_general',
 'No_subyacente',
 'Subyacente',
 't',
 't2',
 'L18.Indice_general',
 'L18.Subyacente',
 'mes_01',
 'mes_02',
 'mes_03',
 'mes_04',
 'mes_05',
 'mes_06',
 'mes_07',
 'mes_08',
 'mes_09',
 'mes_10',
 'mes_11',
 'mes_12']

In [97]:
print(Y_test,results.predict(X[-horizon:]))

ValueError: shapes (12,6) and (19,) not aligned: 6 (dim 1) != 19 (dim 0)